
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charl
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoPrincipal = new javax.swing.JLabel();
        jButtonVeiculos = new javax.swing.JButton();
        jButtonViagens = new javax.swing.JButton();
        jButtonAbastecimento = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jButtonCidades = new javax.swing.JButton();
        jButtonCidades1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));

        logoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo SIS-PROVENET-2.png"))); // NOI18N

        jButtonVeiculos.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVeiculos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgVeicMenu.png"))); // NOI18N
        jButtonVeiculos.setText("FROTA");
        jButtonVeiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVeiculosMouseClicked(evt);
            }
        });

        jButtonViagens.setBackground(new java.awt.Color(204, 204, 204));
        jButtonViagens.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonViagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagemViagens.png"))); // NOI18N
        jButtonViagens.setText("VIAGENS");
        jButtonViagens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonViagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonViagensMouseClicked(evt);
            }
        });
        jButtonViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViagensActionPerformed(evt);
            }
        });

        jButtonAbastecimento.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAbastecimento.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonAbastecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abastecimentoIMG (1).png"))); // NOI18N
        jButtonAbastecimento.setText("ABASTECIMENTO");
        jButtonAbastecimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonAbastecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbastecimentoMouseClicked(evt);
            }
        });

        jButtonFuncionarios.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFuncionarios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgFuncionarios.png"))); // NOI18N
        jButtonFuncionarios.setText("FUNCIONÁRIOS");
        jButtonFuncionarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFuncionariosMouseClicked(evt);
            }
        });

        jButtonCidades.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCidades.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgCidades.png"))); // NOI18N
        jButtonCidades.setText("CIDADES");
        jButtonCidades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCidadesMouseClicked(evt);
            }
        });

        jButtonCidades1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCidades1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonCidades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair (1).png"))); // NOI18N
        jButtonCidades1.setText("SAIR");
        jButtonCidades1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonCidades1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCidades1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jButtonVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoPrincipal)
                .addGap(261, 261, 261))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoPrincipal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViagensActionPerformed

    private void jButtonFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFuncionariosMouseClicked
        CadastrarFuncionario telaFuncionarios = new CadastrarFuncionario();
        telaFuncionarios.setVisible(true);
    }//GEN-LAST:event_jButtonFuncionariosMouseClicked

    private void jButtonVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVeiculosMouseClicked
        Veiculos telaVeiculos = new Veiculos();
        telaVeiculos.setVisible(true);
    }//GEN-LAST:event_jButtonVeiculosMouseClicked

    private void jButtonAbastecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbastecimentoMouseClicked
        Abastecimentos telaAbastecimentos;
        try {
            telaAbastecimentos = new Abastecimentos();
            telaAbastecimentos.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAbastecimentoMouseClicked

    private void jButtonViagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViagensMouseClicked
        Viagens telaViagens;
        try {
            telaViagens = new Viagens();
            telaViagens.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonViagensMouseClicked

    private void jButtonCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCidadesMouseClicked
        Cidades telaCidades = new Cidades();
        telaCidades.setVisible(true);
    }//GEN-LAST:event_jButtonCidadesMouseClicked

    private void jButtonCidades1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCidades1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonCidades1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbastecimento;
    private javax.swing.JButton jButtonCidades;
    private javax.swing.JButton jButtonCidades1;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonVeiculos;
    private javax.swing.JButton jButtonViagens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoPrincipal;
    // End of variables declaration//GEN-END:variables
}
