
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charl
 */
public class Viagens extends javax.swing.JFrame {

    /**
     * Creates new form Viagens
     */
    public Viagens() throws SQLException {
        initComponents();
        chamarFuncionarios();
        chamarVeiculo();
        popularTabelaViagens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableViagens = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSaida = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVeiculo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextKmChegada = new javax.swing.JTextField();
        jTextKmSaida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viagens.png"))); // NOI18N

        jTableViagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FUNCIONARIO", "VEICULO", "SAÍDA", "DESTINO", "DATA", "KM SAÍDA", "KM CHEGADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableViagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableViagensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableViagens);

        jButtonSalvar.setBackground(new java.awt.Color(153, 255, 0));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(51, 102, 255));
        jButtonEditar.setText("EDITAR");
        jButtonEditar.setEnabled(false);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 0, 51));
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("LOCAL DE SAÍDA:");

        jTextFieldSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaidaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("DESTINO:");

        jTextFieldDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("DATA:");

        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("FUNCIONARIO:");

        jComboBoxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        jComboBoxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("VEICULO");

        jComboBoxVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        jComboBoxVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVeiculoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("KM SAÍDA:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("KM CHEGADA:");

        jTextKmChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKmChegadaActionPerformed(evt);
            }
        });

        jTextKmSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKmSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(271, 271, 271))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDestino))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextKmSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextKmChegada)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextKmChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextKmSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String funcionario = jComboBoxFuncionario.getSelectedItem().toString();
        int posFuncionario = funcionario.indexOf("-");
        String idFuncionario = funcionario.substring(0, posFuncionario);
        String veiculo = jComboBoxVeiculo.getSelectedItem().toString();
        int posVeiculo = veiculo.indexOf("-");
        String idVeiculo = veiculo.substring(0, posVeiculo);
        String localSaida = jTextFieldSaida.getText();
        String destino = jTextFieldDestino.getText();
        String data_viagem = jTextData.getText();
        String km_saida = jTextKmSaida.getText();
        String km_chegada = jTextKmChegada.getText();

        if (funcionario.equals("") || veiculo.equals("") || data_viagem.equals("") || localSaida.equals("") || destino.equals("") || km_saida.equals("") || km_chegada.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
        } else {
            try {
                SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy");
                String str = data_viagem;
                Date data = formatador.parse(str);

                Conexao con = new Conexao();
                java.sql.Statement st = (java.sql.Statement) con.conexao.createStatement();
                String sql = "INSERT INTO viagens (funcionario, veiculo, local_saida, destino, data, km_saida, km_chegada) VALUES ('" + idFuncionario + "','" 
                        + idVeiculo + "','" 
                        + localSaida + "','" 
                        + destino + "','" 
                        + new java.sql.Date(data.getTime()) + "','"
                        + km_saida + "','"
                        + km_chegada + "' )";

                if (st.execute(sql)) {
                    JOptionPane.showMessageDialog(null, "Ops! Algo errado");
                } else {
                    JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso!");
                    popularTabelaViagens();
                    limparCampos();
                }
            } catch (Exception e) {
                System.out.println("erro");
            }
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaidaActionPerformed

    private void jTextFieldDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinoActionPerformed

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jComboBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFuncionarioActionPerformed

    private void jComboBoxVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVeiculoActionPerformed

    }//GEN-LAST:event_jComboBoxVeiculoActionPerformed

    private void jTextKmChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKmChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKmChegadaActionPerformed

    private void jTextKmSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKmSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKmSaidaActionPerformed

    private void jTableViagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableViagensMouseClicked
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        int row = jTableViagens.getSelectedRow();
        String id = jTableViagens.getValueAt(row, 0).toString();
        String funcionario = jTableViagens.getValueAt(row, 1).toString();
        String veiculo = jTableViagens.getValueAt(row, 2).toString();
        String local_saida = jTableViagens.getValueAt(row, 3).toString();
        String destino = jTableViagens.getValueAt(row, 4).toString();
        String data = jTableViagens.getValueAt(row, 5).toString();
        String km_saida = jTableViagens.getValueAt(row, 6).toString();
        String chegada = jTableViagens.getValueAt(row, 7).toString();

        
        jTextFieldSaida.setText(local_saida);
        jTextFieldDestino.setText(destino);
        jTextData.setText(data);
        jTextKmSaida.setText(km_saida);
        jTextKmChegada.setText(chegada);
    }//GEN-LAST:event_jTableViagensMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int row = jTableViagens.getSelectedRow();
        String id = jTableViagens.getValueAt(row, 0).toString();

        String funcionario = jComboBoxFuncionario.getSelectedItem().toString();
        int posFuncionario = funcionario.indexOf("-");
        String idFuncionario = funcionario.substring(0, posFuncionario);
        String veiculo = jComboBoxVeiculo.getSelectedItem().toString();
        int posVeiculo = veiculo.indexOf("-");
        String idVeiculo = veiculo.substring(0, posVeiculo);
        String local_saida = jTextFieldSaida.getText();
        String destino = jTextFieldDestino.getText();
        String data_viagem = jTextData.getText();
        String km_saida = jTextKmSaida.getText();
        String km_chegada = jTextKmChegada.getText();
        
        
        
        if (!funcionario.isEmpty() || !veiculo.isEmpty()) {
            try {
                SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy");
                String str = data_viagem;
                Date data = formatador.parse(str);
                
                Conexao con = new Conexao();
                Statement st = con.conexao.createStatement();
                String sql = "UPDATE viagens SET funcionario='" + idFuncionario + "',"
                        + "veiculo='" + idVeiculo + "',"
                        + "local_saida='" + local_saida + "',"
                        + "destino='" + destino + "',"
                        + "data='" + new java.sql.Date(data.getTime()) + "',"
                        + "km_saida='" + km_saida + "',"
                        + "km_chegada='" + km_chegada + "'"
                        + " WHERE id=" + id;
                        System.out.println(sql);
                if (st.executeUpdate(sql) == 1) {
                    JOptionPane.showMessageDialog(null, "Dados alterados");
                    
                    jButtonEditar.setEnabled(false);
                    jButtonExcluir.setEnabled(false);
                    jButtonSalvar.setEnabled(true);
                    
                    limparCampos();
                    popularTabelaViagens();

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Cidades.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(Abastecimentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ops!, Preencha os campos para continuar! ");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int linha = jTableViagens.getSelectedRow();
        String id = jTableViagens.getValueAt(linha, 0).toString();

        int confirmacao = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente deletar?");
        if (confirmacao == 0) {
            try {
                Conexao con = new Conexao();
                Statement st = con.conexao.createStatement();
                String sqlDelete = "DELETE FROM viagens WHERE id = " + id;
                

                if (!st.execute(sqlDelete)) {
                    JOptionPane.showMessageDialog(rootPane, "DELETADO COM SUCESSO!");
                    limparCampos();
                    popularTabelaViagens();
                    con.conexao.close();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO AO DELETAR");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Cidades.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Viagens().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Viagens.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableViagens;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldSaida;
    private javax.swing.JTextField jTextKmChegada;
    private javax.swing.JTextField jTextKmSaida;
    // End of variables declaration//GEN-END:variables
public void chamarFuncionarios() throws SQLException{
        Conexao con = new Conexao();
        Statement st = con.conexao.createStatement();
        
        String sql = "SELECT id, nome FROM funcionarios";
        
        ResultSet resultado = st.executeQuery(sql);

        while (resultado.next()) {
            jComboBoxFuncionario.addItem(resultado.getString("id") + "-" + resultado.getString("nome")); 
        }
}

public void chamarVeiculo() throws SQLException{
        Conexao con = new Conexao();
        Statement st = con.conexao.createStatement();
        
        String sql = "SELECT id, veiculo FROM veiculos";
        
        ResultSet resultado = st.executeQuery(sql);

        while (resultado.next()) {
            jComboBoxVeiculo.addItem(resultado.getString("id") + "-" + resultado.getString("veiculo")); 
        }
}

public void popularTabelaViagens() throws SQLException {

        DefaultTableModel model = (DefaultTableModel) jTableViagens.getModel();
        model.setNumRows(0);
        
        Conexao con = new Conexao();
        java.sql.Statement st = con.conexao.createStatement();

        String sql = "SELECT funcionarios.nome, veiculos.veiculo, viagens.* FROM `viagens` JOIN funcionarios ON funcionarios.id = viagens.funcionario JOIN veiculos ON veiculos.id = viagens.veiculo ORDER BY viagens.id DESC";
        
        System.out.println(sql);

        ResultSet resultado = st.executeQuery(sql); 
        
        while (resultado.next()) {
            String dataTabela = resultado.getString("data"); 
            Date dt;
            try {
                dt = new SimpleDateFormat("yyyy-MM-dd").parse(dataTabela);
                String dataFormatada = new SimpleDateFormat("dd-MM-yyyy").format(dt);
                model.addRow(new Object[]{
                resultado.getString("id"),
                resultado.getString("nome"),
                resultado.getString("veiculo"),
                resultado.getString("local_saida"), 
                resultado.getString("destino"),                 
                dataFormatada,
                resultado.getString("km_saida"),
                resultado.getString("km_chegada")
            });
            } catch (ParseException ex) {
                Logger.getLogger(Abastecimentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


public void limparCampos(){
        jComboBoxFuncionario.setSelectedIndex(0);
        jComboBoxVeiculo.setSelectedIndex(0);
        jTextFieldSaida.setText("");
        jTextFieldDestino.setText("");
        jTextData.setText("");
        jTextKmSaida.setText("");
        jTextKmChegada.setText("");
}
}
